version: '3.4'
services:
  goatcounter:
    image: aaronlee/goatcounter:latest
    restart: always
    container_name: goatcounter
    volumes:
      - ./data:/home/goatcounter/db
    ports:
      - 8080:8080
